# Generated by Django 4.1.7 on 2023-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите жанр книги', max_length=200, verbose_name='Жанр Книги')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': '',
            },
        ),
    ]
