# Generated by Django 4.1.7 on 2023-04-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_status_bookinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
